apiVersion: "apps/v1beta2"
kind: StatefulSet
metadata:
  name: "{{ template "neo4j.core.fullname" . }}"
spec:
  podManagementPolicy: Parallel
  serviceName: {{ template "neo4j.fullname" . }}
  replicas: {{ .Values.coreServers }}
  selector:
    matchLabels:
      release: {{ .Values.name | quote }}
      app: {{ template "neo4j.name" . }}
      component: core
  template:
    metadata:
      labels:
        release: {{ .Values.name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "neo4j.name" . }}
        component: core
    spec:
      containers:
      - name: {{ template "neo4j.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        # Most pod config is factored into a different configMap, which is user overrideable.
        envFrom:
          - configMapRef:
              {{- if .Values.core.configMap }}
              name: "{{ .Values.core.configMap }}"
              {{- else }}
              name: {{ template "neo4j.coreConfig.fullname" . }}
              {{- end }}
        env:
          {{- if .Values.authEnabled }}
          - name: NEO4J_SECRETS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "neo4j.secrets.fullname" . }}
                key: neo4j-password
          {{- end }}
        command:
          - "/bin/bash"
            - "-c"
            - |
              # Making this host the default address, so that advertised addresses are over-rideable
              # by custom configmaps if specified.
              export HOST=$(hostname -f)
              export NEO4J_causal__clustering_discovery__advertised__address=${NEO4J_causal__clustering_discovery__advertised__address:-$HOST}
              export NEO4J_dbms_default__advertised__address=${NEO4J_dbms_default__advertised__address:-$HOST}
              export NEO4J_dbms_connector_bolt_advertised__address=${NEO4J_dbms_connector_bolt_advertised__address:-$HOST}
              export NEO4J_dbms_connector_http_advertised__address=${NEO4J_dbms_connector_http_advertised__address:-$HOST}
              export NEO4J_dbms_connector_https_advertised__address=${NEO4J_dbms_connector_https_advertised__address:-$HOST}

              # These settings are *not* overrideable, because they must match the initial_discovery_members
              # In the Neo4j node config, otherwise Neo4j's akka layer will reject connections.
              export NEO4J_causal__clustering_discovery__advertised__address=$(hostname -f):5000
              export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
              export NEO4J_causal__clustering_raft__advertised__address=$(hostname -f):7000

              if [ "${AUTH_ENABLED:-}" == "true" ]; then
                export NEO4J_AUTH="neo4j/${NEO4J_SECRETS_PASSWORD}"
              else
                export NEO4J_AUTH="none"
              fi

              echo "Starting Neo4j CORE on $HOST"
              exec /docker-entrypoint.sh "neo4j"
        ports:
        - containerPort: 5000
          name: discovery
        - containerPort: 7000
          name: raft
        - containerPort: 6000
          name: tx
        - containerPort: 7474
          name: browserhttp
        - containerPort: 7473
          name: browserhttps
        - containerPort: 7687
          name: bolt
        # securityContext:
        #   privileged: true
        volumeMounts:
        - name: datadir
          mountPath: "{{ .Values.volumeMountPath }}"
          {{- if .Values.volumeSubPath }}
          subPath: {{ .Values.volumeSubPath }}
          {{- end }}
        # Users may uncomment this and adjust that mount point to
        # attach custom plugins.  For now, plugins are injected into the
        # solution container.
        #- name: plugins
        #  mountPath: /plugins
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ports.bolt }}
          initialDelaySeconds: 30
          periodSeconds: 3
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: {{ .Values.ports.bolt }}
        resources:
          requests:
            cpu: "{{ .Values.cpuRequest }}"
            memory: "{{ .Values.memoryRequest }}"
          limits:
            cpu: "{{ .Values.cpuLimit }}"
            memory: "{{ .Values.memoryLimit }}"
{{- if .Values.coreSidecarContainers }}
{{ toYaml .Values.coreSidecarContainers | indent 6 }}
{{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end -}}
{{- if .Values.coreInitContainers }}
      initContainers:
{{ toYaml .Values.coreInitContainers | indent 6 }}
{{- end }}
      volumes:
        - name: plugins
          emptyDir: {}
{{- if .Values.maintenanceServiceKeySecret }}
        - name: "{{ .Values.maintenanceServiceKeySecret }}"
          secret:
            secretName: "{{ .Values.maintenanceServiceKeySecret }}"
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
        {{- if .Values.volumeAnnotations }}
{{ toYaml .Values.volumeAnnotations | indent 12 }}
        {{- end }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.volumeStorageClass }}"
        resources:
          requests:
            storage: "{{ .Values.volumeSize }}"
